disable nginx via env var

diff --git a/opt/recompose b/opt/recompose
--- a/opt/recompose
+++ b/opt/recompose
@@ -14,34 +14,34 @@ AWS_CMD=/app/vendor/awscli/bin/aws
 SFDC_CUSTOM=sfdc-custom.tar.gz
 
 process_slug() {
-  local app_release=${1:?}
+    local app_release=${1:?}
 
-  echo "--> Processing $app_release"
+    echo "--> Processing $app_release"
 
-  local app_release_array=($app_release)
-  local app=${app_release_array[0]}
-  local release=${app_release_array[1]}
+    local app_release_array=($app_release)
+    local app=${app_release_array[0]}
+    local release=${app_release_array[1]}
 
-  local slug_id=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/releases/$release \
-    -H "Accept: application/vnd.heroku+json; version=3" | \
-    python -c 'import json,sys;obj=json.load(sys.stdin);print obj["slug"]["id"]')
+    local slug_id=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/releases/$release \
+        -H "Accept: application/vnd.heroku+json; version=3" |
+        python -c 'import json,sys;obj=json.load(sys.stdin);print obj["slug"]["id"]')
 
-  if [ -n "$slug_id" ]; then
-    local slug_url=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/slugs/$slug_id \
-      -H "Accept: application/vnd.heroku+json; version=3" | \
-      python -c 'import json,sys;obj=json.load(sys.stdin);print obj["blob"]["url"]')
+    if [ -n "$slug_id" ]; then
+        local slug_url=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/slugs/$slug_id \
+            -H "Accept: application/vnd.heroku+json; version=3" |
+            python -c 'import json,sys;obj=json.load(sys.stdin);print obj["blob"]["url"]')
 
-    if [ -n "$slug_url" ]; then
-      echo "--> Downloading slug ${slug_id} for ${app}"
-      curl --retry 3 -s -L "${slug_url}" | \
-          tar xzm --strip-components=1 -C . 2>&1 | \
-          grep -v "Ignoring unknown extended header keyword"
+        if [ -n "$slug_url" ]; then
+            echo "--> Downloading slug ${slug_id} for ${app}"
+            curl --retry 3 -s -L "${slug_url}" |
+                tar xzm --strip-components=1 -C . 2>&1 |
+                grep -v "Ignoring unknown extended header keyword"
+        else
+            echo "! ERROR: could not find slug $slug_id for $app_release"
+        fi
     else
-      echo "! ERROR: could not find slug $slug_id for $app_release"
+        echo "! ERROR: could not find release v${release} for ${app}"
     fi
-  else
-    echo "! ERROR: could not find release v${release} for ${app}"
-  fi
 }
 
 [ -z "$HEROKU_API_KEY" ] && echo " ! ERROR: missing HEROKU_API_KEY config var" && exit 1
@@ -50,25 +50,28 @@ process_slug() {
 [ -z "$AWS_SECRET_ACCESS_KEY" ] && echo " ! ERROR: missing AWS_SECRET_ACCESS_KEY config var" && exit 1
 [ -z "$AWS_TOOL_S3_BUCKET_NAME" ] && echo " ! ERROR: missing AWS_S3_BUCKET_NAME config var" && exit 1
 
-
-# Only start nginx if he WEB_PROCESS_CMD is defined
-if [ -f .nginx/bin/nginx-start ] && [ -n "$WEB_PROCESS_CMD" ]; then
-  cd .nginx > /dev/null 2>&1
-  eval "bin/nginx-start &"
-  pid=$!
-  cd - > /dev/null 2>&1
-  trap "kill -9 $pid; exit" SIGKILL
+# nginx is only built when enabled...
+if [ -z ${NGINX_DISABLED} ]; then
+    # Only start nginx if he WEB_PROCESS_CMD is defined
+    if [ -f .nginx/bin/nginx-start ] && [ -n "$WEB_PROCESS_CMD" ]; then
+        cd .nginx >/dev/null 2>&1
+        eval "bin/nginx-start &"
+        pid=$!
+        cd - >/dev/null 2>&1
+        trap "kill -9 $pid; exit" SIGKILL
+    else
+        echo "No .nginx/bin/nginx-start file found!"
+    fi
 else
-  echo "No .nginx/bin/nginx-start file found!"
+    echo "NGINX has been disabled with NGINX_DISABLED environment flag"
 fi
 
 # create netrc
-cat >> $HOME/.netrc <<EOF
+cat >>$HOME/.netrc <<EOF
 machine api.heroku.com
   login $HEROKU_API_USER
   password $HEROKU_API_KEY
 EOF
-
 
 ############ Downloading jdk1.8.0_131_x64,  recomposer.jar #######################################
 JAVA_VERSION="$(basename $JAVA_HOME)"
@@ -77,23 +80,21 @@ echo "**** Downloading $JAVA_VERSION from s3..."
 ${AWS_CMD:?} s3 cp s3://${AWS_TOOL_S3_BUCKET_NAME:?}/$JAVA_VERSION.tar.gz - | tar xzm --strip-components=1 -C $JAVA_HOME 2>&1
 echo "Completed downloading jdk1.8.0_131_x64 from s3Key:d5eab6c07320844df2961afd84f95df8"
 echo "**** Downloading recomposer.jar from s3..."
- ${AWS_CMD:?} s3 cp s3://${AWS_TOOL_S3_BUCKET_NAME:?}/releaser-$RECOMPOSE_VERSION.jar recomposer.jar 2>&1
+${AWS_CMD:?} s3 cp s3://${AWS_TOOL_S3_BUCKET_NAME:?}/releaser-$RECOMPOSE_VERSION.jar recomposer.jar 2>&1
 ###################################################################################################
-
-
 
 rm $HOME/.netrc
 
 echo "Invoke Java Recomposer"
 echo $JAVA_HOME
-echo `which java`
+echo $(which java)
 java -jar recomposer.jar
 echo "Java Recomposer Completed"
-echo "true" > $HOME/.recompose
+echo "true" >$HOME/.recompose
 
 if [ -n "$cmd" ]; then
-  echo "--> cmd: ${cmd}"
-  exec bash ${cmd:?}
+    echo "--> cmd: ${cmd}"
+    exec bash ${cmd:?}
 fi
 
 echo "--> $0 exiting"
